language: ruby
rvm:
- 2.1.1
branches:
  only:
  - develop
before_script:
- git config remote.origin.url "https://github.com/Mystist/mystist.github.com.git"
- git config --global user.email "gjl87910lq@gmail.com"
- git config --global user.name "Mystist"
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
env:
  global:
    secure: "OlDue2wjZ9YV9Fz6S/hMimUTY8ZUf6aspl5Os43ubWRDrsGcZ4MzSZvWZJhdVVFuWY8F18w1G8tYde9HSPkshrTBurMdx9nXfFchYT8GQ2kWCswZev3XE1P7ibB998+Tb6wdIrsUDnT6rmAXc4jQKpgJZuxyQ1RCADiLL1wvk67x/kI6uDpig6troSJMYHWiQu3txA5wQXlGGo2gwt0StZd6cCptrsvraXIU1RN8YWFhD2l2g/aIE2VMgdWQStG26BB7u4X68WYApxW2Ej9cq0tkJLqolMl0vmV48Kft/ibI4jS3lcMY59F+NP2RGtrfftgB6konrqIXRCz1XE8CGsVDH5ffoaCgCNkvZosc/cFx35lIeEM3qsk0n0vWx7HpSCH1KtT1pYJdiyfSqeFOLU0kWatw9HScNYFv7BryiWPiMwEgBuOYy++sGw9CgD+jS9gCL6781muJh3lgNu4EhSGAwQishqIxOAMtqaeds4jZRnTOs80xjBrTeiClzurwpRttydAW5e/fhD6dqtNJ7ZfSunBHtLtsdJnd3pBPueLou7pROYIAw83rVnNWFRS5UgzIdIYDptsTVXro/RVuHhyelHLEKoRVvWalb1UNObH6tkDQLvAj95PqR0xMM/6nwpGF34+NSYZ/kgPoE+pVxHjqRzd4m1jY/Yx2blc9rUA="
