language: ruby
rvm:
  - 2.1.1
branches:
  only:
  - develop
env:
  global:
  - secure: "S51S0TGm6wNTlwgcxat5GkbcT+abDDyYvkhwoD7oS5Sijv0GSWjbpCvJhdf4DIk8Pe9lx1VnNKrYGVNbImotfag4wg6aqnZqO9hTu2iGcljLSr0UvyKfwVxsbkreW2nSoRn7tC2NsHiDuF/imDyBxYNzNI0pLdwickwYTE8oXKqv4IKix/ELtTG9bO+GpAPytMRRul1hgeBCYC1l14wbQ5XxkJL2lE6uAK6q7NZ0tJrgR0P3mBRRXxRz+sQ7m/wyraMPx7cQZ07IOIMnEn9eKdCBJ0IiCVRgtAABRjlo31MdTK1ykRZwZ9+DAhpejAnXDfvw6Ml2AN+NUjAfVEbwQDoud2H+ItX0VDw5yIlrIvRjqE0XzxRQvog+guYXWtqRdv3wLjU3L7WQmWfqmoqUwFkrq5q4gaJsaGqHSWTqavwwhzZtVt3VvFVl9EFMJJ9qfHdwQ/tK1THfZFrTmvM2c/IBSmmAiRlT50XrS2W6svOTdgLqkQttfsbn7ePG1olLGbs0rPEkPFkR2irDukND3/UmRqqYzV0OghYQPLb83VcjPzGzLFsXo8D9HseJqlW9WQ1fywdoT9mXs4ep+ian+AKDizTm3WIuQrMfBZZWHWyHkEwCPf32qIwoxabZS80cvTdTIzYJ6F+nSiebJrMtJbLzVh6iLPyceDDGuLEQvd0="